import type { Metadata } from "next";
import { ReactElement, ReactNode } from "react";
import { Inter } from "next/font/google";
import { Header } from "@/components/hoc/header";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ororura",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>): ReactElement {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header>{children}</Header>
      </body>
    </html>
  );
}
